spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_pizza
    username: root
    password: rootroot



  jpa:
    show-sql: true

  servlet:
    multipart:
      file-size-threshold: 10MB
      max-request-size: 100MB


  liquibase:
    change-log: "classpath:/liquibase/changelog.xml"


smartPizza:
  users:
    avatar:
      path: "/home/radik/IdeaProjects/diplomProject/SmartPizza/usersAvatars/"

    default:
      avatars:
        path: "/Users/Raf/IdeaProjects/smart_pizza/src/main/java/com/example/smartpizza/imageUpload/"

products:
   images:
     path: "/Users/Raf/IdeaProjects/smart_pizza/src/main/resources/static/image/"

