spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smart_pizza
    username: root
    password: root_password

  jpa:
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: manasyanjavatestforme@gmail.com
    password: bnbtmwpkhgtaqzau
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      file-size-threshold: 10MB
      max-request-size: 100MB


  liquibase:
    change-log: "classpath:/liquibase/changelog.xml"


smartPizza:
  users:
    avatar:
      path: "/usersAvatars/"

    default:
      avatars:
        path: "/src/main/resources/static/userDefaultAvatar/no-profile-picture-icon.png"

products:
  images:
    path: "/src/main/resources/static/productImages/"

application:
  url: http://localhost:8080

#MAVEN_OPTS: "-Xmx512m"
